# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l0araxxC <- function(X, y, weights, offset, family, lambda, maxit, eps) {
    .Call('_libaglm_l0araxxC', PACKAGE = 'libaglm', X, y, weights, offset, family, lambda, maxit, eps)
}

